version: '3.9'
services:
  proxy:
    image: haproxy:1
    container_name: proxy
    restart: always
    ports:
      - 14500:14500
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:Z
    networks:
      custom_network:
        ipv4_address: 192.168.1.2

  wireshark:
    image: "ffeldhaus/wireshark:0.5"
    container_name: wireshark
    restart: always
    privileged: true
    network_mode: "service:proxy"
    environment:
      - XPRA_PW=wireshark
    volumes:
      - ./data:/home/wireshark

  attacker:
    image: ghcr.io/michael-borck/ethical-base:latest
    container_name: week1-attacker
    stdin_open: true
    tty: true
    networks:
      - custom_network
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24